project:
  title: "TinyLM - language model learnings"
  type: website
  output-dir: _output
  execute-dir: project

format:
  html:
    toc: true
    number-sections: true

website:
  sidebar:
    style: "docked"
    search: true
    contents:
    - section: "Getting Started"
      contents:
      - text: "Home"
        href: index.qmd
    - section: "Theory"
      contents:
      - text: "Cross Entropy Loss"
        href: theory/cross-entropy-loss.ipynb
    - section: "Notebooks"
      contents:
      - text: "Tokenization"
        href: notebooks/01-Tokenizing.ipynb
      - text: "Attention"
        href: notebooks/02-Attention.ipynb

